services:
  - type: web
    name: worknest-backend
    runtime: java
    rootDir: backend/employee_management
    buildCommand: chmod +x mvnw && ./mvnw clean install
    startCommand: java -jar target/*.jar
    plan: free